Repository falcosecurity/falco, pull requests merged in 2019-10, with the labels that each got.

#864 rules update: add back rule Delete Bash History for backport compatib…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/S

#871 documenting the keepalive field of the gPRC outputs API
  userspace/falco/output.proto
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none, size/XS

#873 Specify namespace compat w/ gcc 5
  userspace/falco/grpc_server.cpp
Labels: approved, area/engine, dco-signoff: yes, lgtm, release-note, size/S

#877 proposals area into PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#879 Add explicit catch2 dependency for tests
  tests/CMakeLists.txt
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#880 Added more context on Sysdig Secure
  ADOPTERS.md
Labels: approved, area/integrations, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XS

#825 Proposal add psp rules support
  proposals/20190909-psp-rules-support.md
Labels: approved, area/proposals, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#895 Use falcoctl 0.0.3 w/ unique names
  test/falco_test.py
  test/falco_tests_psp.yaml
  test/psps/privilege_escalation.yaml
  test/psps/supplemental_groups_may_run_as_30_40_10_15.yaml
  test/psps/supplemental_groups_must_run_as_30_40_10_15.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/M

#898 rules update: expand list allowed_k8s_users
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#899 Use falcoctl 0.0.4+ tests for space/dash psp names
  test/falco_test.py
  test/falco_tests_psp.yaml
  test/psps/privileged_name_with_dashes.yaml
  test/psps/privileged_name_with_spaces.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#902 rules update: add calico/node to trusted privileged container list; a…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#907 Don't pop excess values from stack
  userspace/engine/rules.cpp
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#909 Adding Frame.io and SightMachine to ADOPTERS file
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/XS
