Repository falcosecurity/falco, pull requests merged in 2019-09, with the labels that each got.

#830 fix(docker/stable): fix libgcc-6-dev dependencies
  docker/stable/Dockerfile
Labels: approved, area/integrations, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#841 Add ADOPTERS.md
  ADOPTERS.md
Labels: approved, area/integrations, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#844 Adding Shopify to ADOPTERS.md
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#843 Add League to adopters list
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#852 rules update: add fluent/fluentd-kubernetes-daemonset to clear log tr…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#861 update(changelog): prepare for v0.17.1
  CHANGELOG.md
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#868 removing maintainers file
  MAINTAINERS
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/S
