Repository falcosecurity/falco, pull requests merged in 2019-06, with the labels that each got.

#594 Add Sematext Monitoring & Logging agents to trusted k8s containers
  rules/k8s_audit_rules.yaml
Labels: rules

#617 fix egrep rule and ncat rule
  rules/falco_rules.yaml
Labels: rules

#625 Allow Ansible to run using Python 3
  rules/falco_rules.yaml
Labels: rules

#637 Rule updates 2019 05.v3
  rules/falco_rules.yaml
Labels: rules

#659 new: initial owners files for Falco
  OWNERS
  rules/OWNERS
Labels: dco-signoff: yes, kind/documentation, release-note-none, size/S

#664 Triaging issues
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#665 new: improve docs for new contributors
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#666 Prepare for 0.15.2
  CHANGELOG.md
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#668 Prepare for 0.15.3
  CHANGELOG.md
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#667 rule update (mkdirat + clear log activities placeholder)
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, kind/bug, kind/feature, lgtm, release-note, size/L

#671 docs: remove extra words
  integrations/k8s-using-daemonset/README.md
Labels: approved, area/integrations, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#675 rule update: add back trusted_containers list for backport compatibility
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, release-note, size/XS

#677 new: SYSDIG_DIR can be passed as cmake option
  CMakeLists.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/XS

#679 hotfix: SYSDIG_DIR not as an option but as a set
  CMakeLists.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#681 update: fields checksum
  userspace/engine/falco_engine_version.h
Labels: approved, area/engine, dco-signoff: yes, kind/feature, lgtm, release-note, size/XS

#678 rule update: add exception for rule change thread namespace
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/S

#689 new: initial clang format file
  .clang-format
Labels: approved, dco-signoff: yes, kind/documentation, kind/feature, lgtm, release-note-none, size/S
