Repository falcosecurity/falco, pull requests merged in 2020-03, with the labels that each got.

#1061 disable cryptomining rule by default; add exception of localhost and …
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1069 docker minimal images need exact FALCO_VERSION
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#1074 docs: updating branding
  brand/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1077 fix(.circleci): fix get falco version for image build
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#1081 fix: use of "tag" instead of "tags" in default rules
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#974 rule(Change thread namespace): Modify condition to detect suspicious container activity
  rules/falco_rules.yaml
  test/falco_tests.yaml
  test/falco_traces.yaml.in
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/S

#1091 Fix image for event generator deployment yaml
  docker/event-generator/event-generator-k8saudit-deployment.yaml
Labels: approved, area/examples, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1100 fix(.circleci): bintray secret and user for creating stable versions
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1101 remove github tag rel nots flag from CI
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1102 remove --labels flag from circleci
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1093 update(docker/tester): python 3 support for regression tests
  docker/tester/Dockerfile
  docker/tester/root/usr/bin/usage
  test/README.md
  test/falco_test.py
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/M

#1098 docs(readme): adding new release archive
  README.md
Labels: approved, area/build, dco-signoff: yes, kind/documentation, lgtm, release-note, retest-not-required-docs-only, size/XS

#1105 build: fix tbb dependency rename
  CMakeLists.txt
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1099 new(userspace/falco): add --disable-cri-async flag
  userspace/falco/falco.cpp
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/S

#1109 Increase robustness of the release workflow
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, release-note-none, size/M

#1115 falco rule update: whitelist sysdig/agent and sysdig/falco for query …
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1118 update(cmake): using sha256 instead of md5
  CMakeLists.txt
  cmake/modules/DownloadCatch.cmake
  cmake/modules/DownloadFakeIt.cmake
  cmake/modules/OpenSSL.cmake
  cmake/modules/cURL.cmake
  cmake/modules/jq.cmake
  cmake/modules/yaml-cpp.cmake
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#1117 rule update: only detect sa created in kube namespace with success
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
