Repository falcosecurity/falco, pull requests merged in 2020-06, with the labels that each got.

#1250 correct rule conditions to support syscall variants
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/M

#1257 Log modified copy instead of original message.
  userspace/falco/logger.cpp
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1261 correct k8s audit endpoint
  falco.yaml
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1267 rule update (Anonymous Request Allowed): update to checking auth deci…
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1266 Add Logz.io to Falco's adopters list ADOPTERS.md (continuing commit #1235)
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1260 rule(macro user_known_write_below_binary_dir_activities)
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1154 Create a macro to whitelist terminal usage in containers
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/XS

#1222 Change chread namespace
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/XS

#1279 rule(macro `root_dir`): correct macro to exactly match the `/root` dir and not other with just `/root` as a prefix
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1282 docs: teal logo is svg
  brand/teal-logo.svg
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1284 rule(list network_tool_binaries): add zmap to the list
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1286 k8s_audit_rules: kube-apiserver-healthcheck user whitelist
  rules/k8s_audit_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1290 Gitlab
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, retest-not-required-docs-only, size/XS
