Repository falcosecurity/falco, pull requests merged in 2020-09, with the labels that each got.

#1394 Append Slash to Sensitive Mount Path startswith
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1395 build(.circleci): fix static build path
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1381 update: bump Falco engine version to 7
  rules/falco_rules.yaml
  userspace/engine/falco_engine_version.h
Labels: approved, area/engine, area/rules, dco-signoff: yes, kind/bug, kind/feature, lgtm, release-note, size/XS

#1408 update(scripts): driver loader cycles available gcc versions
  scripts/falco-driver-loader
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, release-note, size/M

#1402 enable "Packet socket created in container" by default.
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1415 feat(release): Release 0.26
  CHANGELOG.md
  RELEASE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/M

#1414 docs(brand): documenting Falco color scheme
  brand/README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/S

#1419 feat(falco): Provide a parameter for loading lua files from an alternate path
  userspace/falco/falco.cpp
  userspace/falco/falco_outputs.cpp
  userspace/falco/falco_outputs.h
Labels: approved, area/engine, dco-signoff: yes, kind/feature, lgtm, release-note, size/M
