Repository falcosecurity/falco, pull requests merged in 2020-02, with the labels that each got.

#1028 Address rules fps
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/S

#1032 docs: update references to branches into README
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1033 Base64 format fix
  userspace/engine/formats.cpp
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1041 Fix memory leaks in k8s audit and json events
  userspace/engine/json_evt.cpp
  userspace/engine/json_evt.h
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#1036 Add Coveo to the list of Falco adopters
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1054 Verify checksum after downloading sysdig tarball
  cmake/modules/sysdig-repo/CMakeLists.txt
  cmake/modules/sysdig.cmake
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1055 update: changelog 0.20.0
  CHANGELOG.md
  README.md
  docker/kernel/linuxkit/Dockerfile
  docker/minimal/Dockerfile
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1050 Rename BPF_PROBE and SYSDIG_BPF_PROBE to FALCO_BPF_PROBE and make the variable consistent
  cmake/modules/sysdig-repo/CMakeLists.txt
  cmake/modules/sysdig-repo/patch/libscap.patch
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
  scripts/falco-probe-loader
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#981 fix: use base name in docker-entrypoint.sh
  docker/dev/docker-entrypoint.sh
  docker/local/docker-entrypoint.sh
  docker/rhel/docker-entrypoint.sh
  docker/stable/docker-entrypoint.sh
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#1068 fix(.circleci): dockerhub authentication during releasing process
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS
