Repository falcosecurity/falco, pull requests merged in 2020-07, with the labels that each got.

#1292 fix: update k8s audit endpoint to /k8s-audit everywhere
  test/confs/psp.yaml
  userspace/falco/configuration.cpp
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1296 correct stdout output buffering option
  userspace/falco/lua/output.lua
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1300 docs: add myself to owners
  OWNERS
Labels: approved, area/proposals, dco-signoff: yes, kind/documentation, lgtm, release-note, retest-not-required-docs-only, size/XS

#1294 rules update: create placeholder macros for customization
  rules/falco_rules.yaml
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1297 rename `SKIP_MODULE_LOAD` to `SKIP_DRIVER_LOADER`
  docker/falco/docker-entrypoint.sh
  docker/local/docker-entrypoint.sh
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/S

#1293 build: stale bot adjustements
  .github/stale.yml
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1301 build(cmake/modules): update driver version to 33c00f
  cmake/modules/sysdig.cmake
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1307 fix(docker): correct syntax error in the entrypoint script
  docker/falco/docker-entrypoint.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1289 rule(Write below etc): allow snapd to write its unit files
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/XS

#1316 update(rules): disable drift detection rules by default
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1195 Initial userspace instrumentation implementation
  userspace/falco/falco.cpp
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/M

#1303 feat(userspace/falco): print version at startup
  userspace/falco/falco.cpp
Labels: approved, area/engine, dco-signoff: yes, kind/feature, lgtm, release-note, size/XS

#1319 Use ISO 8601 format for changelog dates.
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1321 Exclude image analyzer
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1326 rule(macro falco_privileged_images): add 'docker.io/falcosecurity/falco'
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1323 rule(list allowed_k8s_users): add "kubernetes-admin" user
  rules/k8s_audit_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1327 rules update(Read sensitive file untrusted): add trusted images into …
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1330 falco-driver-loader: fix conflicting $1 argument usage
  scripts/falco-driver-loader
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1336 macro(trusted_pod): add new list k8s_image_list
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
