Repository falcosecurity/falco, pull requests merged in 2020-08, with the labels that each got.

#1339 Kh add rule detect ephemeral container
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1350 macro(exe_running_docker_save): add better support for centos
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1349 macro(user_read_sensitive_file_containers): replace endswiths with ex…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1355 update: bump sysdig to 0.27.0
  cmake/modules/sysdig.cmake
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/XS

#1358 Update readme
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/M

#1359 chore(rules): add `renameat2` to `rename` macro
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/XS

#1361 docs(community health files): fall back to org default community heal…
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/L

#1366 fix(userspace/falco): do not always rethrow the exception
  userspace/falco/falco.cpp
Labels: approved, area/engine, dco-signoff: yes, lgtm, release-note, size/XS

#1368 docs: changelog for 0.25.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/M

#1369 rules: Adding user.loginuid to the default falco rules
  rules/falco_rules.yaml
  test/rules/detect_connect_using_in.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, kind/rule-update, lgtm, release-note, size/L

#1373 added brakets to three macros to make them less ambiguous
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/cleanup, kind/rule-update, lgtm, release-note, size/S
