Repository falcosecurity/falco, pull requests merged in 2020-12, with the labels that each got.

#1500 rule(Container Run as Root User): new rule created
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1494 Better handle not having a config file
  userspace/falco/configuration.cpp
  userspace/falco/falco.cpp
Labels: approved, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#1495 chore(cmake/modules): avoid useless rebuild
  CMakeLists.txt
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#1501 rule(list user_known_change_thread_namespace_binaries): add crio and …
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1496 chore(cmake): mark some variables as advanced
  cmake/modules/OpenSSL.cmake
  cmake/modules/gRPC.cmake
  cmake/modules/jq.cmake
  cmake/modules/static-analysis.cmake
  cmake/modules/yaml-cpp.cmake
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/S

#1506 docs(README.md): correct broken links
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1507 feature(grpc): Add engine version to version svc
  userspace/falco/grpc_server_impl.cpp
  userspace/falco/version.proto
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/S
