Repository falcosecurity/falco, pull requests merged in 2020-04, with the labels that each got.

#1090 versions table for the README
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/S

#1131 fix(driver/bpf): exact check on bpf_probe_read_str() return value
  cmake/modules/sysdig.cmake
Labels: approved, area/build, area/engine, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1133 fix: HOST_ROOT environment variable detection
  cmake/modules/sysdig-repo/patch/libscap.patch
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#1137 rule(Write below root): use pmatch to check against known root direct…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1138 driver version bump to a259b4bf49c3
  cmake/modules/sysdig.cmake
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1143 Fix tag typos
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1070 Add a macro to whitelist system binaries using the network
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/feature, lgtm, release-note, size/S

#1140 fix(integrations/k8s-using-daemonset): --cri flag correct socket path
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml
  integrations/k8s-using-daemonset/k8s-without-rbac/falco-daemonset.yaml
Labels: approved, area/integrations, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XS

#1136 Add missing privileges for the apps Kubernetes API group
  integrations/k8s-using-daemonset/k8s-with-rbac/falco-account.yaml
  integrations/k8s-using-deployment/k8s-with-rbac/falco-k8s-audit-account.yaml
Labels: approved, area/integrations, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1147 CHANGELOG for 0.22.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/M

#1149 docs: changelog for 0.22.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/S

#1152 rule update: add a rule to detect reverse shell
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1153 update audit level to Metadata for secrets
  examples/k8s_audit_config/audit-policy.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/S

#1158 Updates to the falco-driver-loader script
  CMakeLists.txt
  scripts/falco-driver-loader
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, release-note, size/L

#1156 update(docker/event-generator): remove the event-generator
  .gitignore
  docker/README.md
  docker/event-generator/Dockerfile
  docker/event-generator/Makefile
  docker/event-generator/docker-entrypoint.sh
  docker/event-generator/event-generator-k8saudit-deployment.yaml
  docker/event-generator/event-generator-role-rolebinding-serviceaccount.yaml
  docker/event-generator/event-generator-syscall-daemonset.yaml
  docker/event-generator/event_generator.cpp
  docker/event-generator/k8s_event_generator.sh
  docker/event-generator/yaml/configmap-private-creds.yaml
  docker/event-generator/yaml/disallowed-pod-deployment.yaml
  docker/event-generator/yaml/hostnetwork-deployment.yaml
  docker/event-generator/yaml/nodeport-service.yaml
  docker/event-generator/yaml/privileged-deployment.yaml
  docker/event-generator/yaml/role-pod-exec.yaml
  docker/event-generator/yaml/role-wildcard-resources.yaml
  docker/event-generator/yaml/role-write-privileges.yaml
  docker/event-generator/yaml/sensitive-mount-deployment.yaml
  docker/event-generator/yaml/vanilla-configmap.yaml
  docker/event-generator/yaml/vanilla-deployment.yaml
  docker/event-generator/yaml/vanilla-role-rolebinding-serviceaccount.yaml
  docker/event-generator/yaml/vanilla-service.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note, size/XXL

#1160 Correct "drivers build gruid" URLs
  scripts/falco-driver-loader
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1161 update(cmake/modules): catch2 version bump to v2.12.1
  cmake/modules/DownloadCatch.cmake
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none, size/XS

#1150 docs: add release process
  RELEASE.md
Labels: approved, area/build, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/M

#1164 fix rule naming following naming convention
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1170 fixing curl command error 0 bytes for CDN download.
  scripts/falco-driver-loader
Labels: approved, area/build, area/integrations, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1175 fix: grpc compilation with splitted gpr library
  cmake/modules/gRPC.cmake
  userspace/falco/CMakeLists.txt
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#1174 fix(cmake/modules): update driver to support kernels 5.6.y
  cmake/modules/sysdig.cmake
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS
