Repository falcosecurity/falco, pull requests merged in 2021-01, with the labels that each got.

#1516 docs: fix a broken link of README
  README.md
Labels: approved, area/build, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1512 Publish Falco container image to AWS ECR Public registry
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, release-note, size/M

#1376 Proposal on better exception handling
  proposals/20200828-structured-exception-handling.md
Labels: approved, area/proposals, dco-signoff: yes, kind/feature, lgtm, release-note-none, retest-not-required-docs-only, size/L

#1386 Allow exe_running_docker_save in the "Create Hidden Files or Directories" and "Mkdir binary dirs" rules
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/bug, kind/rule-update, lgtm, release-note, size/XS

#1518 docs(.circleci): adding Jonah to Falco CI maintainers
  .circleci/OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XS

#1522 chore(cmake): remove unnecessary whitespace patch
  cmake/modules/sysdig-repo/patch/libscap.patch
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/S

#1528 update(.circleci): fix tag definition for ECR image push on releases
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1527 docs(RELEASE.md): link the ecr images in releases
  RELEASE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#1529 fix(userspace/falco): output needs to be initialized after fork
  userspace/falco/falco.cpp
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/M

#1524 docs: move governance to falcosecurity/.github
  GOVERNANCE.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/M

#1514 Fix various typos in markdown files.
  ADOPTERS.md
  README.md
  RELEASE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS
