Repository falcosecurity/falco, pull requests merged in 2021-09, with the labels that each got.

#1719 Adding libssl-dev, fixing upstream image reference.
  docker/falco/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1729 Add new miner pools to miner domain lists to improve detection
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/S, approved

#1725 Remove duplicate allowed ecr registry rule
  rules/falco_rules.yaml
Labels: area/rules, kind/cleanup, kind/rule-update, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1716 fix(scripts): correct lookup order when trying multiple `gcc` versions in the `falco-driver-loader` script
  scripts/falco-driver-loader
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#1697 Systemd unit: Do not send falco alerts to /var/log/messages by default
  scripts/rpm/falco.service
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1734 Bump driver version to `5727c45`
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#1738 update(proposal): clarify that old drivers are not removed anymore
  proposals/20200901-artifacts-cleanup.md
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/S, approved, area/proposals

#1744 build(cmake): bump libs version to 3aa7a83
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#1745 docs(changelog.md): update for release 0.30.0
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved
