Repository falcosecurity/falco, pull requests merged in 2021-05, with the labels that each got.

#1640 macro for EKS images to use in rule: Launch Privileged Container
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/S

#1645 changelog: add notes for 0.28.1 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#1651 add Yahoo!Japan as an adopter
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1641 docs(proposals): fix libs contribution name
  proposals/20210119-libraries-contribution.md
Labels: approved, area/proposals, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/S

#1652 docs(release.md): add blog announcement to post-release tasks
  RELEASE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1657 rule update(Debugfs Launched in Privileged Container): fix typo in de…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1661 changelog: add notes for 0.28.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S
