Repository falcosecurity/falco, pull requests merged in 2021-02, with the labels that each got.

#1530 new(proposals): libraries donation
  proposals/2021019-libraries-donation.md
Labels: approved, area/proposals, dco-signoff: yes, kind/documentation, lgtm, release-note, size/L

#1536 add eks:node-manager to allowed_k8s_users list
  rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1545 docs: update link for building from source
  ADOPTERS.md
  docker/README.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/S

#1546 falco: add healthz endpoint
  falco.yaml
  userspace/falco/configuration.cpp
  userspace/falco/configuration.h
  userspace/falco/webserver.cpp
  userspace/falco/webserver.h
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/M

#1543 Update falco_rules.yaml (CVE-2021-3156)
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1385 package manager launched makro - rhsm cert updates, apt
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1337 chore(rules): Rule exceptions for ibm cloud
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/S
