Repository falcosecurity/falco, pull requests merged in 2021-03, with the labels that each got.

#1562 Add flex to docker for building bpf module on recent amazon linux2
  docker/falco/Dockerfile
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1563 Fix broken links to docs.
  test/README.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/XS

#1565 Use default pip version to get avocado version.
  docker/tester/root/usr/bin/usage
Labels: approved, area/tests, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1566 adding shapesecurity to adopters
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1519 adding other alternate AWS builds to circleCI
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, lgtm, release-note, size/M

#1574 Pocteo as an adopter
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1560 rule (Write below monitored dir): Clean up and use glob matching.
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/cleanup, kind/rule-update, lgtm, release-note-none, size/XS

#1583 Kh add rule for container escape
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1588 fix: update rule description
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1488 falco-driver-loader improvements (custom driver name + clean previous drivers functionality)
  scripts/falco-driver-loader
Labels: approved, dco-signoff: yes, kind/documentation, kind/feature, lgtm, release-note, size/L

#1591 fix: publishing jobs
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1594 fix(.circleci): tar must be present in the image
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, priority/high, release-note-none, size/S

#1595 fix(falco/test): bump pyyaml from 5.3.1 to 5.4
  test/requirements.txt
Labels: approved, area/tests, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS
