Repository falcosecurity/falco, pull requests merged in 2021-06, with the labels that each got.

#1663 revert: add notes for 0.28.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#1659 add known k8s service accounts
  rules/k8s_audit_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1666 build(test): upgrade urllib3 to 1.26.5
  test/requirements.txt
Labels: approved, area/build, area/tests, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1665 rule update(Non sudo setuid): check user id as well in case user name…
  rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1669 build: upgrade driver version to 17f5d
  cmake/modules/falcosecurity-libs.cmake
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, release-note, size/XS

#1676 rules(list miner_domains): add rx.unmineable.com for anti-miner detection
  rules/falco_rules.yaml
Labels: approved, area/rules, dco-signoff: yes, kind/rule-update, lgtm, release-note, size/XS

#1677 docs(changelog.md): add release 0.29.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#1679 Fix link to CONTRIBUTING.md in the Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/bug, kind/documentation, lgtm, release-note, size/XS

#1682 docs(changelog.md): update for release 0.29.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1684 docs(release.md): update steps
  RELEASE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1687 CHANGELOG for Falco 0.29.1 changeset
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S
