Repository falcosecurity/falco, pull requests merged in 2021-12, with the labels that each got.

#1795 correctly clean loaded drivers in `falco-driver-loader`
  scripts/falco-driver-loader
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1796 rules: add support to openat2 in default ruleset
  rules/falco_rules.yaml
  test/rules/tagged_rules.yaml
Labels: area/rules, kind/feature, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/S, approved

#1801 remove unused files in test directory
  test/cpu_monitor.sh
  test/plot-live.r
  test/plot-traces.r
  test/run_performance_tests.sh
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XXL, area/tests

#1773 fix(userspace/falco): in case output_file cannot be opened, throw a falco exception
  userspace/falco/outputs_file.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1800 fix(userspace/falco): accept 'Content-Type' header that contains "application/json", but it is not strictly equal to it
  userspace/falco/webserver.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1817 Add ECR repository to rules
  rules/falco_rules.yaml
Labels: kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1820 fix(rules): typo in "Create Symlink Over Sensitive Files" rule output
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1806 add Phoenix to adopters list
  ADOPTERS.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1815 rules: add containerd socket to sensitive_mount macro
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1818 docs: add jasondellaluce to OWNERS
  OWNERS
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1830 fix(build): use consistent 7-character build abbrev sha
  cmake/modules/GetFalcoVersion.cmake
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build
