Repository falcosecurity/falco, pull requests merged in 2021-11, with the labels that each got.

#1756 Fix falco-driver-loader SELinux insmod denials
  scripts/falco-driver-loader
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1764 Update ubuntu image for driver-loader test
  .circleci/config.yml
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/tests

#1776 add raft in the adopters list
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1758 Sign Packages and Linux Repositories with SHA256.
  scripts/publish-deb
  scripts/publish-rpm
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#1778 build: always populate partial version variables
  cmake/modules/GetFalcoVersion.cmake
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#1754 style(userspace/engine): avoid creating multiple versions of methods only to assume default ruleset. Use a default argument instead.
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#1780 Allow append of new exceptions to rules
  test/falco_tests_exceptions.yaml
  test/rules/exceptions/rule_exception_new_no_field_append.yaml
  test/rules/exceptions/rule_exception_new_second_field_append.yaml
  test/rules/exceptions/rule_exception_new_single_field_append.yaml
  userspace/engine/falco_engine_version.h
  userspace/engine/lua/rule_loader.lua
Labels: area/rules, kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/L

#1797 update(build): bump FakeIt version
  cmake/modules/DownloadFakeIt.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, area/tests

#1771 Add wget and curl to remote_file_copy_binaries
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/M, approved
