Repository falcosecurity/falco, pull requests merged in 2022-04, with the labels that each got.

#1960 rule(Disallowed K8s User): exclude allowed eks users
  rules/k8s_audit_rules.yaml
Labels: dco-signoff: yes, lgtm, size/S, approved

#1961 Fix some typos
  CHANGELOG.md
  brand/README.md
  docker/builder/root/usr/bin/scl_enable
  proposals/20190826-grpc-outputs.md
  proposals/20191030-api.md
  proposals/20210501-plugin-system.md
  userspace/engine/filter_macro_resolver.h
  userspace/engine/lua/rule_loader.lua
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#1944 perf: change falco_engine::process_event to lookup sources by index
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/falco/falco.cpp
  userspace/falco/webserver.cpp
  userspace/falco/webserver.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#1968 rule(falco_rules) Removed use cases not triggering macro curl_download
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1973 Fixed ouput Rules K8s Serviceaccount Created/Deleted
  rules/k8s_audit_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1974 add gVisor to ADOPTERS.md
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1977 build(cmake): upgrade catch2 to 2.13.9
  cmake/modules/DownloadCatch.cmake
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#1980 build: correct conffiles for DEB packages
  cmake/cpack/debian/conffiles
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1963 new(rules): add rule to detect excessively capable container
  rules/falco_rules.yaml
Labels: area/rules, kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved

#1950 chore(falco_scripts): Update `falco-driver-loader` cleaning phase
  scripts/debian/postinst.in
  scripts/debian/postrm.in
  scripts/debian/prerm.in
  scripts/falco-driver-loader
  scripts/rpm/postinstall.in
  scripts/rpm/postuninstall.in
  scripts/rpm/preuninstall.in
Labels: kind/feature, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/build
