Repository falcosecurity/falco, pull requests merged in 2022-07, with the labels that each got.

#2107 update(falco): update libs to 0.7.0-rc2, 2.0.0-rc1+driver
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2099 new(circleci): enable integration tests for arm64.
  .circleci/config.yml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2101 docs(readme): added arm64 mention + packages + badge.
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2119 update(falco): update libs to 0.7.0
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2120 update(docs): changelog for version 0.32.1
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2124 chore(engine): remove trailing colon from logs when loading rule files
  userspace/falco/app_actions/load_rules_files.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1981 Falco Rules/Conditions update
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2128 fix(userspace): compute the `drop ratio` in the right way
  userspace/falco/event_drops.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2117 Fixed condition rule Launch Privileged Container
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2130 new: add a `drop_pct` referred to the global number of events
  userspace/falco/statsfilewriter.cpp
  userspace/falco/statsfilewriter.h
Labels: kind/feature, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2137 Add darryk10 as rules OWNERS as reviewer
  rules/OWNERS
Labels: kind/documentation, area/rules, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2142 fix: added arch to bpf download url
  scripts/falco-driver-loader
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2096 Remove required_engine_version from falco engine load_rules APIs
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/falco/app_actions/load_rules_files.cpp
  userspace/falco/app_actions/print_support.cpp
  userspace/falco/application.h
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2131 cleanup(ci): natively builds docker images for x86_64 and arm64 and then use docker manifest to combine them
  .circleci/config.yml
Labels: kind/cleanup, size/XL, dco-signoff: yes, lgtm, release-note-none, approved, area/build

#2146 fix(ci): fixed docker manifest circleci.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2147 new(userspace): print architecture information
  CMakeLists.txt
  userspace/falco/app_actions/load_config.cpp
  userspace/falco/config_falco.h.in
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved
