Repository falcosecurity/falco, pull requests merged in 2022-08, with the labels that each got.

#2153 docs(falco-driver-loader): add some comments in `falco-driver-loader`
  scripts/falco-driver-loader
Labels: kind/documentation, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2154 cleanup(rules): cleanup rules disabled by default
  rules/falco_rules.yaml
Labels: kind/cleanup, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/S, approved

#2157 chore(test/utils): remove unused script
  test/utils/run_sysdig.sh
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2079 new(userspace/falco): extend buffer kernel side event drop metrics
  userspace/falco/event_drops.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2159 update(docs): changelog for version 0.32.2
  CHANGELOG.md
Labels: kind/documentation, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2156 fix: print full rule load errors/warnings without verbose/-v
  userspace/falco/app_actions/load_rules_files.cpp
  userspace/falco/app_actions/validate_rules_files.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2162 Enrich pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, kind/design, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2166 cleanup(rules): cleanup rules disabled by default - 2
  rules/falco_rules.yaml
Labels: area/rules, kind/cleanup, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/S, approved

#2171 new(CI): add CodeQL security scanning to Falco.
  .github/workflows/codeql.yaml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/M, approved, area/ci

#2165 Falco driver loader enhancements
  scripts/falco-driver-loader
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2095 update(userspace/falco): use move semantics in falco logger
  userspace/falco/event_drops.cpp
  userspace/falco/falco.cpp
  userspace/falco/grpc_server.cpp
  userspace/falco/logger.cpp
  userspace/falco/logger.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2118 new(rules): Directory traversal monitored file read
  rules/falco_rules.yaml
Labels: area/rules, kind/feature, kind/rule-create, release-note, dco-signoff: yes, lgtm, size/M, approved

#2081 refactor(userspace/engine): increase const coherence in falco engine
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/engine/formats.cpp
  userspace/engine/formats.h
Labels: kind/cleanup, kind/design, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2168 cleanup(rules): cleanup rules disabled by default - 3
  rules/falco_rules.yaml
Labels: area/rules, kind/cleanup, kind/rule-update, release-note, dco-signoff: yes, lgtm, size/M, approved

#2178 new(scripts): improved falco-driver-loader supporting any ubuntu flavor.
  scripts/falco-driver-loader
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS
