Repository falcosecurity/falco, pull requests merged in 2022-10, with the labels that each got.

#2229 fix(userspace): add explicit constructors and initializations
  userspace/engine/falco_load_result.h
  userspace/engine/falco_rule.h
  userspace/engine/falco_source.h
  userspace/engine/filter_evttype_resolver.h
  userspace/engine/filter_macro_resolver.h
  userspace/engine/filter_ruleset.h
  userspace/engine/filter_warning_resolver.h
  userspace/engine/indexed_vector.h
  userspace/engine/rule_loader.cpp
  userspace/engine/rule_loader.h
  userspace/engine/rule_loader_collector.cpp
  userspace/engine/rule_loader_collector.h
  userspace/engine/rule_loader_compiler.h
  userspace/engine/rule_loader_reader.h
  userspace/engine/stats_manager.h
  userspace/falco/application.cpp
  userspace/falco/application.h
  userspace/falco/stats_writer.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2234 fix(rules): add falco no-driver images to k8s_containers macro
  rules/falco_rules.yaml
Labels: kind/bug, area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2237 fix(userspace): safely check string bounded access
  userspace/engine/rule_loader.cpp
  userspace/falco/configuration.h
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2238 fix(falco_service): falco service needs to write under `/sys/module/falco`
  cmake/cpack/CMakeCPackOptions.cmake
  scripts/CMakeLists.txt
  scripts/debian/falco.service
  scripts/debian/falco_inject_kmod.service
  scripts/rpm/falco.service
  scripts/rpm/falco_inject_kmod.service
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2244 chore: bump libs version
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2250 fix(scripts): inject kmod script fails with some systemd versions
  scripts/debian/falco_inject_kmod.service
  scripts/rpm/falco_inject_kmod.service
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2251 chore: use latest driver tag `3.0.1+driver`
  cmake/modules/driver.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2253 update(userspace/falco): move on from deprecated libs API for printing event list
  userspace/falco/app_actions/print_syscall_events.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#2256 chore: bump plugin version
  cmake/modules/plugins.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build, kind/release

#2261 update(changelog.md): add entry for Falco 0.33.0
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2264 update(CHANGELOG.md): sync changelog changes
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L, kind/release

#2266 fix(ci): fixed version bucket for release jobs.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2272 fix(engine): save syscall source only when processing events
  userspace/engine/falco_engine.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS
