Repository falcosecurity/falco, pull requests merged in 2022-01, with the labels that each got.

#1798 update(tests): remove `token_bucket` unit tests
  tests/CMakeLists.txt
  tests/engine/test_token_bucket.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/tests

#1839 chore: improve --list output using is_source_valid
  userspace/falco/falco.cpp
Labels: kind/bug, kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1842 Add Giant Swarm to Adopters list
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#1829 fix: set http output contenttype to text/plain when json output is disabled
  userspace/falco/falco_outputs.cpp
  userspace/falco/outputs.h
  userspace/falco/outputs_http.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#1846 new(userspace/falco): add support for kernel side simple consumer
  userspace/falco/falco.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1834 replace ".." concatenation with table.concat
  userspace/engine/lua/rule_loader.lua
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L

#1847 fix(engine): correctly format json output in json_event
  userspace/engine/json_evt.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1852 new(configuration): support defining plugin init config as a YAML
  userspace/falco/configuration.h
Labels: kind/feature, kind/cleanup, kind/design, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#1858 docs: fix priority level "info" to "informational"
  falco.yaml
Labels: kind/documentation, area/rules, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1860 refactor: remove apt-config utility from debian_packages monitoring
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1865 build: updated cloudtrail plugin to latest version
  cmake/modules/plugins.cmake
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1863 update(scripts/falco-driver-loader): load the latest version first
  scripts/falco-driver-loader
Labels: kind/bug, kind/feature, release-note, dco-signoff: yes, lgtm, size/M, approved, area/build

#1867 rules: update aws_cloudtrail_rules required plugin versions
  rules/aws_cloudtrail_rules.yaml
Labels: area/rules, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1810 Bypass research issues
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, kind/rule-create, release-note, dco-signoff: yes, lgtm, size/S, approved

#1868 rule(falco_rules): update evt.type for spawned process macro
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1872 update(userspace/engine): cleanup unused alternate-lua-dir option and remove config_falco_engine.h.in, now unused since lua scripts are embedded in Falco.
  userspace/engine/CMakeLists.txt
  userspace/engine/config_falco_engine.h.in
  userspace/engine/falco_common.cpp
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/falco/falco.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#1873 new(build): publish both static and glibc binaries
  .circleci/config.yml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#1882 build: dropped centos8 circleci build because it is useless
  .circleci/config.yml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#1880 docs(changelog.md): update for release 0.31.0
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#1883 build: hotfix for release 0.31.0
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build
