Repository falcosecurity/falco, pull requests merged in 2022-03, with the labels that each got.

#1917 Add Fairwinds to ADOPTERS.md
  ADOPTERS.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1923 chore(build): update falco libs to b7eb0dd
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#1926 fix(cli): restore behavior of -pc -pm -pk CLI options
  userspace/falco/app_cmdline_options.cpp
  userspace/falco/app_cmdline_options.h
  userspace/falco/falco.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#1929 docs(CHANGELOG.md): Changelog for 0.31.1
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#1935 update(changelog): add link to security fix for 0.31.1
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1938 Allow to whitelist shell config modifiers
  rules/falco_rules.yaml
Labels: kind/bug, kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1930 Add user_known_mount_in_privileged_containers macro
  rules/falco_rules.yaml
Labels: area/rules, kind/feature, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1958 chore(rules): remove leftover
  rules/falco_rules.yaml
Labels: area/rules, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1955 rules: Out of the box ruleset for OKTA Falco Plugin
  rules/okta_rules.yaml
Labels: area/rules, kind/feature, kind/rule-create, release-note, dco-signoff: yes, lgtm, approved, size/L
