Repository falcosecurity/falco, pull requests merged in 2022-02, with the labels that each got.

#1888 rule_output(Delete Bucket Public Access Block) typo
  rules/aws_cloudtrail_rules.yaml
Labels: area/rules, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1885 Fix for informational rules loaded at notice level
  userspace/engine/lua/rule_loader.lua
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1887 update(build)!: replaced various `PROBE` with `DRIVER` where necessary.
  ADOPTERS.md
  CMakeLists.txt
  cmake/modules/falcosecurity-libs.cmake
  scripts/debian/postinst.in
  scripts/debian/prerm.in
  scripts/falco-driver-loader
  scripts/rpm/postinstall.in
  scripts/rpm/preuninstall.in
  test/falco_test.py
  userspace/falco/config_falco.h.in
  userspace/falco/falco.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#1825 Fix false-positive of sssd updating /etc/krb5.keytab
  rules/falco_rules.yaml
Labels: kind/bug, area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1866 Rule Update - Adds npm support to pkg mgt processes
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1877 rule(falco_rules): Polkit Local Privilege Escalation Vulnerability (CVE-2021-4034)
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-create, release-note, dco-signoff: yes, lgtm, size/S, approved

#1742 upgrade macro(keepalived_writing_conf)
  rules/falco_rules.yaml
Labels: kind/rule-update, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1899 fix(scripts): correct typo in `falco-driver-loader` help message
  scripts/falco-driver-loader
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1900 fix(userspace/falco): applies FALCO_INSTALL_CONF_FILE as the default …
  CMakeLists.txt
  userspace/falco/falco.cpp
  userspace/falco/verify_engine_fields.sh
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#1903 update(falco): updates usage description for -o, --option
  userspace/falco/falco.cpp
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1915 chore(userspace/falco): fixes truncated -b option description.
  userspace/falco/app_cmdline_options.cpp
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#1907 fix(userspace/falco): correct plugins init config conversion from YAML to JSON
  userspace/falco/configuration.h
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#1908 chore(userspace/engine): remove unused lua functions and state vars
  userspace/engine/lua/modules/compiler.lua
  userspace/engine/lua/rule_loader.lua
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved
