Repository falcosecurity/falco, pull requests merged in 2022-11, with the labels that each got.

#2219 fix(scripts): force falco-driver-loader script to try to compile the driver anyway even on unsupported platforms
  scripts/falco-driver-loader
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2281 fix(userspace/falco): verify engine fields only for syscalls
  userspace/falco/verify_engine_fields.sh
Labels: kind/bug, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2286 fix(engine): fix warning about redundant std::move
  userspace/engine/falco_engine.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2288 update(falco): add container-gvisor and kubernetes-gvisor print options
  userspace/falco/app_actions/init_falco_engine.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2285 Add Xenit AB to adopters
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2299 update(build): bump libs to 0.9.2 for 0.33.1
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2301 new(docs): add entry for 0.33.1 changelog
  CHANGELOG.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2205 update(docs): add overview and versioning sections to falco release.md
  RELEASE.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2303 new(CHANGELOG): add entry for 0.33.1 (in master branch this time)
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2226 Rule: PTRACE attached to process
  rules/falco_rules.yaml
Labels: area/rules, kind/rule-create, release-note, dco-signoff: yes, lgtm, size/S, approved

#2291 rules: add salt-call as a trusted process
  rules/falco_rules.yaml
Labels: kind/bug, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2125 update(userspace/falco): enable using zlib with webserver
  userspace/falco/webserver.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2260 new(config): explicitly add the `simulate_drops` config
  falco.yaml
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS
