Repository falcosecurity/falco, pull requests merged in 2022-06, with the labels that each got.

#2030 chore(userpace/falco): do not print error code in process_events.cpp
  userspace/falco/app_actions/process_events.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2033 update(build): updated plugins to latest versions.
  cmake/modules/plugins.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#2035 docs(changelog): added 0.32.0 release notes.
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2045 fix(build): try to use root user for cimg/base
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2046 update(build): avoid double build of docker images when pushing to aws ecr
  .circleci/config.yml
Labels: kind/bug, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/build

#2047 fix(build): use apt instead of apk when installing deps for aws ecr publish
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#1997 Circle CI build job for ARM64
  .circleci/config.yml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/build

#2049 update(docker): updated falco-builder to fix multiarch support.
  docker/builder/Dockerfile
  docker/builder/root/usr/bin/scl_enable
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#2051 fix(build): fixed circleCI artifacts publish for arm64.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2052 fix(build): removed leftover line in circleci config.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2056 fix(build): fixed publish-docker-dev job context.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2058 fix(build): docker-container buildx engine does not support retagging images. Tag all images together.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2055 Correct linting issue in rules
  rules/falco_rules.yaml
Labels: area/rules, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2057 fix(scripts): fixed falco-driver-loader driver download url.
  scripts/falco-driver-loader
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2060 new(scripts): support InRelease file creation for publish-deb script.
  scripts/publish-deb
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2044 update(build): Switch from RSA/SHA1 to RSA/SHA256 signature in the RPM package
  .circleci/config.yml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2062 fix(scripts): fixed path in publish-deb script.
  scripts/publish-deb
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2020 fix(tests): make run_regression_tests.sh work locally
  test/README.md
  test/requirements.txt
  test/run_regression_tests.sh
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/tests

#2069 fix(ci): sign arm64 rpm packages.
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#2075 fix(ci): fix sign script - avoid interpreting '{*}$argv' too soon
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2067 update(OWNERS): add Federico Di Pierro to owners.
  OWNERS
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2050 remove kaizhe from falco rule owner
  rules/OWNERS
Labels: do-not-merge/release-note-label-needed, dco-signoff: yes, lgtm, approved, size/XS

#2076 fix(rules): use exit event in reverse shell detection rule
  rules/falco_rules.yaml
Labels: kind/bug, area/rules, kind/rule-update, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2089 fix(tests): make tests run locally (take 2)
  test/README.md
  test/run_regression_tests.sh
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/tests

#2100 fix(docker): fixed deb tester sub image.
  docker/tester/root/runners/deb.Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build
