Repository falcosecurity/falco, pull requests merged in 2023-06, with the labels that each got.

#2600 update(cmake): bumped libs to 0.11.0-rc5 and driver to 5.0.1.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2596 fix: unquote quoted URL's to avoid libcurl errors
  userspace/falco/outputs_http.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2608 update(cmake): bump libs to 0.11.0
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#2609 update(cmake): bump falco rules to 1.0.0-rc1
  cmake/modules/rules.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#2610 update(cmake): bump plugin versions
  cmake/modules/plugins.cmake
Labels: release-note, dco-signoff: yes, lgtm, size/S, approved

#2611 docs(README.md): add scope/status badge and simply doc structure
  README.md
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2614 update(cmake): bump libs to 0.11.1
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#2620 sync(docs): update Changelog for 0.35.0.
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L, kind/release

#2634 update(userspace): change description of snaplen option stating only performance implications
  userspace/falco/app/options.cpp
Labels: kind/documentation, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2636 fix(ci): skip plugins and falcoctl tests for static build
  .github/workflows/reusable_test_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2637 Update ADOPTERS.md
  ADOPTERS.md
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#2641 fix(.github): skip some regression tests in static build
  .github/workflows/reusable_test_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2642 fix(ci): fixed publish deb packages with new debian bookworm
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2629 vote: update(OWNERS): add incertum (Melissa Kilby) to approvers
  OWNERS
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2623 chore(userspace/falco): make source matching error more expressive
  userspace/falco/app/actions/process_events.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2648 update(cmake): bump falco rules to v1.0.1
  cmake/modules/rules.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2635 fix(scripts/falco-driver-loader): fixed ubuntu kernel version
  scripts/falco-driver-loader
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, size/S, approved

#2627 fix(scripts): support debian kernel flavors other than normal in falco-driver-loader
  scripts/falco-driver-loader
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, size/S, approved

#2662 update(cmake): bump libs to 0.11.3
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2650 update(OWNERS): add LucaGuerra to owners
  OWNERS
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2665 docs: update changelog for 0.35.1
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved
