Repository falcosecurity/falco, pull requests merged in 2023-11, with the labels that each got.

#2894 new(docs): sync changelog for 0.36.2.
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, kind/release

#2900 fix(userspace/engine): cache latest rules compilation output
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, size/M, approved, area/build

#2901 chore(gha): set cosign-installer to v3.1.2
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2899 update(userspace/falco): introduce new engine_version_semver key in v…
  userspace/falco/versions_info.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2911 fix(gha): disable branch protection rule trigger for scorecard
  .github/workflows/scorecard.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2913 cleanup(userspace/engine): remove legacy k8saudit implementation
  userspace/engine/CMakeLists.txt
  userspace/engine/json_evt.cpp
  userspace/engine/json_evt.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XXL

#2917 cleanup(falco): remove `init` in the configuration constructor
  userspace/falco/configuration.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2919 update(doc): Add Thought Machine as adopters
  ADOPTERS.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2929 chore(falco): update to libs on nov 28th
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2927 new(falco): print system info when Falco starts
  userspace/falco/CMakeLists.txt
  userspace/falco/app/actions/actions.h
  userspace/falco/app/actions/print_kernel_version.cpp
  userspace/falco/app/app.cpp
  userspace/falco/app/state.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2933 cleanup(falco): remove decode_uri as it is no longer used
  unit_tests/engine/test_falco_utils.cpp
  userspace/engine/falco_utils.cpp
  userspace/engine/falco_utils.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L
