Repository falcosecurity/falco, pull requests merged in 2023-04, with the labels that each got.

#2470 cleanup(ci): properly set a concurrency for CI workflows.
  .github/workflows/ci.yml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2464 cleanup(unit_tests): try making test_configure_interesting_sets more robust
  unit_tests/falco/app/actions/test_configure_interesting_sets.cpp
Labels: kind/bug, kind/failing-test, kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/L, area/tests

#2494 update(scripts): updated falco-driver-loader to support al2022 and al2023
  scripts/falco-driver-loader
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved

#2509 update: improve control and UX of ignored events
  unit_tests/falco/app/actions/test_configure_interesting_sets.cpp
  userspace/falco/app/actions/configure_interesting_sets.cpp
  userspace/falco/app/actions/print_ignored_events.cpp
  userspace/falco/app/app.cpp
  userspace/falco/app/app.h
  userspace/falco/app/options.cpp
Labels: kind/cleanup, kind/design, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2511 fix(ci): bucket -> bucket_suffix
  .github/workflows/master.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2513 fix(ci): enable toolset before every make command
  .github/workflows/reusable_build_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2514 chore(ci): properly install recent version of git (needed >= 2.18 by checkout action)
  .github/workflows/reusable_build_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci
