Repository falcosecurity/falco, pull requests merged in 2023-10, with the labels that each got.

#2854 fix(gha): use fedora instead of centos 7 for package publishing
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2867 update(doc) Add Wireshark / Logray as adopters
  ADOPTERS.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2863 feat(userspace): remove experimental outputs queue recovery strategies
  falco.yaml
  userspace/engine/falco_common.cpp
  userspace/engine/falco_common.h
  userspace/falco/app/actions/init_outputs.cpp
  userspace/falco/configuration.cpp
  userspace/falco/configuration.h
  userspace/falco/falco_outputs.cpp
  userspace/falco/falco_outputs.h
  userspace/falco/stats_writer.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2871 chore: bump libs to the latest tag 0.13.2
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release

#2872 new(docs): add changelog for 0.36.1
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build, kind/release

#2877 fix(userspace/engine): fix memory leak
  userspace/engine/rule_loader_compiler.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2886 sync(release/0.36.x): update libs to 0.13.3
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#2888 Run OpenSSF Scorecard in pipeline
  .github/workflows/scorecard.yaml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#2892 update(cmake): bumped libs to 0.13.4 tag.
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#2893 new(docs): add changelog for 0.36.1 + 0.36.2.
  CHANGELOG.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, size/S, approved
