Repository falcosecurity/falco, pull requests merged in 2023-02, with the labels that each got.

#2396 update(build): update falcoctl version to 0.3.0-rc7
  cmake/modules/falcoctl.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2399 fix(scripts): fixed falcoctl config install dir.
  scripts/CMakeLists.txt
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2401 update(build): update falcoctl to 0.3.0
  cmake/modules/falcoctl.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2404 update(userspace): change `modern_bpf.cpus_for_each_syscall_buffer` default value
  falco.yaml
  userspace/falco/app_actions/load_rules_files.cpp
  userspace/falco/configuration.cpp
Labels: kind/design, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2405 fix(scripts): force rpm postinstall script to always show dialog, even on upgrade
  scripts/rpm/postinstall.in
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2407 new(docs): update Changelog for 0.34.0
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2409 fix(cmake): fixed tag fetching fallback (that is indeed needed)
  cmake/modules/GetFalcoVersion.cmake
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2415 cleanup(userspace/falco): do not enter dropping mode.
  userspace/falco/app_actions/open_inspector.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2412 fix(dockerfile/no-driver): install ca-certificates
  docker/no-driver/Dockerfile
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2408 fix(release): fixed tag creation step in release doc.
  RELEASE.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2347 new(userspace,tests): add proper support for generic events indexing.
  unit_tests/engine/test_filter_evttype_resolver.cpp
  userspace/engine/filter_evttype_resolver.cpp
  userspace/engine/filter_evttype_resolver.h
  userspace/falco/app_actions/print_syscall_events.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2394 new(ci): added new workflow to automatic tag and publish new builder and tester images upon changes
  .github/workflows/images_bumper.yml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#2418 fix(userspace/engine): correctly bump engine version after introducti…
  userspace/engine/falco_engine_version.h
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2424 update(cmake): bumped libs to 0.10.4
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2426 new(docs): update Changelog for 0.34.1
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2427 new(docs): add security audit from January 2023
  audits/SECURITY_AUDIT_2023_01_23-01-1097-LIV.pdf
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS
