Repository falcosecurity/falco, pull requests merged in 2023-07, with the labels that each got.

#2668 doc: Adding Thalesgroup as Falco adopters
  ADOPTERS.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2674 update(falco): update libs to dc02e50
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
  userspace/engine/falco_engine_version.h
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#2686 update(cmake): update cpp-httplib to 0.13.1
  cmake/modules/cpp-httplib.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2703 update(userspace/falco): improve cli flag description related to drivers
  userspace/falco/app/options.cpp
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS
