Repository falcosecurity/falco, pull requests merged in 2023-09, with the labels that each got.

#2753 fix(userspace/engine): support appending to unknown sources
  userspace/engine/falco_engine.cpp
  userspace/engine/rule_loader.cpp
  userspace/engine/rule_loader.h
  userspace/engine/rule_loader_collector.cpp
  userspace/engine/rule_loader_compiler.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2761 fix: restore Falco MINIMAL_BUILD and deprecate `userspace` option
  userspace/falco/app/actions/helpers_inspector.cpp
  userspace/falco/app/options.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2758 cleanup(config): add more info
  falco.yaml
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/S, approved

#2762 cleanup: deprecate rate limiter mechanism
  falco.yaml
  userspace/falco/configuration.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2759 fix(userspace/falco): properly delete metrics timer upon leaving.
  userspace/falco/app/restart_handler.cpp
  userspace/falco/stats_writer.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2765 ci: support tests on amazon-linux
  .github/workflows/reusable_test_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2766 update: introduce new stats updated to the latest libs version
  userspace/falco/event_drops.cpp
Labels: kind/feature, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2767 fix(engine): fix reorder warning for m_watch_config_files / m_rule_matching
  userspace/falco/configuration.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2755 update(userspace/falco): revised CLI help messages
  userspace/falco/app/options.cpp
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2770 ci: disable falco-driver-loader tests on ARM64
  .github/workflows/reusable_test_packages.yaml
Labels: kind/bug, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2769 chore: bump Falco to latest libs
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2772 docs(README.md): correct URL
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2562 feat: support parsing of system environment variables in yaml
  unit_tests/falco/test_configuration.cpp
  userspace/falco/yaml_helper.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L, area/tests

#2782 update(docker): use debian 12 slim for falco no driver
  docker/no-driver/Dockerfile
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2789 fix(stats): always initialize m_output field
  userspace/falco/stats_writer.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2796 docs: add LICENSE file
  LICENSE
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2798 fix(userspace/falco): clearing full output queue
  userspace/falco/falco_outputs.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2799 update(docs): add driver-loader-legacy to readme and fix bad c&p
  docker/README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2803 cleanup(userspace): thrown exceptions and avoid multiple logs
  userspace/falco/falco_outputs.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2806 update(cmake): bumped libs to 0.13.0-rc2 and driver to 6.0.1+driver.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2813 update(build): update falcoctl to 0.6.1
  cmake/modules/falcoctl.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2815 chore: bump to latest libs
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2820 update(cmake): bumped plugins to latest stable versions.
  cmake/modules/plugins.cmake
Labels: release-note, dco-signoff: yes, lgtm, size/S, approved, area/build, kind/release

#2828 chore: automatically attach release author to release body.
  .github/workflows/release.yaml
  RELEASE.md
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2829 update(cmake): bumped falcoctl to 0.6.2.
  cmake/modules/falcoctl.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#2830 update(gha): add version for rn2md
  .github/workflows/release.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2834 chore(cmake): bumped libs to 0.13.1.
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#2832 new(docs): add changelog for 0.36.0
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L, kind/release

#2837 update(docs): add changelog for 0.36.0
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L, kind/release

#2839 [BREAKING CHANGE] cleanup(falco)!: remove `--userspace` support
  userspace/falco/app/actions/helpers_inspector.cpp
  userspace/falco/app/options.cpp
  userspace/falco/app/options.h
  userspace/falco/stats_writer.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2844 chore(ci): bumped rn2md to latest master.
  .github/workflows/release.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2841 [BREAKING CHANGE] cleanup(falco)!: remove `outputs.rate` and `outputs.max_burst` from Falco config
  falco.yaml
  userspace/falco/app/actions/process_events.cpp
  userspace/falco/configuration.cpp
  userspace/falco/configuration.h
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2846 new(ci): properly link libs and driver releases linked to a Falco release
  .github/release_template.md
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci
