Repository falcosecurity/falco, pull requests merged in 2023-05, with the labels that each got.

#2521 fix(ci): escape heredoc
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2525 fix(ci): add Cloudfront Distribution ID
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2527 fix(ci): separate rpm/bin/bin-static/deb packages before publication, rename bin-static
  .github/workflows/reusable_build_packages.yaml
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#2528 fix(ci): falco images directory, ecr login
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2531 fix(ci): configure ECR public region
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2518 falco-driver-loader add TMPDIR support
  scripts/falco-driver-loader
Labels: release-note, dco-signoff: yes, lgtm, size/S, approved

#2538 cleanup(config): modern bpf is no more experimental
  falco.yaml
  userspace/falco/app/options.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2542 fix(ci): simplify and fix multi-arch image publishing process
  .github/workflows/release.yaml
  .github/workflows/reusable_build_docker.yaml
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/ci

#2545 fix(ci): correctly tag slim manifest
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2546 new(ci): sign releases with cosign
  .github/workflows/release.yaml
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/M, approved, area/ci

#2549 fix(ci): load falco image before building falco-driver-loader
  .github/workflows/reusable_build_docker.yaml
  docker/driver-loader/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2537 new(scripts): updated falco-driver-loader to properly support talos.
  scripts/falco-driver-loader
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2551 cleanup(actions): now modern bpf support `-A` flag
  userspace/falco/app/actions/load_rules_files.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2493 Updating Falco branding guidelines
  brand/README.md
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2515 docs: improve documentation and description of base_syscalls option
  falco.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2556 fix(ci): use normal docker to build docker images, instead of buildx.
  .github/workflows/reusable_build_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#2557 fix(ci): set docker TARGET_ARCH
  .github/workflows/reusable_build_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2560 fix(ci): properly use `docker save` to store images.
  .github/workflows/reusable_build_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2563 fix(ci): get the manifest for the correct tag
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2564 chore(userspace/falco/app): print all supported plugin caps
  userspace/falco/app/actions/helpers_generic.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2568 update(ci): use repo instead of master branch for reusable workflows
  .github/workflows/master.yaml
  .github/workflows/release.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#2572 update(build): bump falcoctl version
  cmake/modules/falcoctl.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2573 update(build): libs 0.11.0-rc2
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2576 fix(userspace/falco): don't hang on terminating error when multi sourcing
  userspace/falco/app/actions/process_events.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2578 chore(userspace/falco): always print invalid syscalls from custom set
  userspace/falco/app/actions/configure_interesting_sets.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#2571 cleanup(config): improve `falco.yaml` config
  falco.yaml
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XXL

#2592 feat: add image source OCI label to docker images
  docker/builder/Dockerfile
  docker/builder/modern-falco-builder.Dockerfile
  docker/driver-loader/Dockerfile
  docker/falco/Dockerfile
  docker/local/Dockerfile
  docker/no-driver/Dockerfile
  docker/tester/Dockerfile
  docker/ubi/Dockerfile
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build, area/ci

#2589 fix(userspace/falco): report plugin deps rules issues in any case
  userspace/falco/app/actions/load_rules_files.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2595 fix(userspace/engine): store required engine version as string in -L …
  userspace/engine/falco_engine.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2547 docs(proposals): Falco roadmap management
  proposals/20230511-roadmap-management.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/proposals

#2581 feat: add jq and curl to falco-no-driver docker image
  docker/no-driver/Dockerfile
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, area/ci

#2594 cleanup(docs): adjust falco readme style and content
  README.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, approved, size/L

#2597 fix(userspace/engine): store alternatives as array in -L json output
  userspace/engine/falco_engine.cpp
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS
