Repository falcosecurity/falco, pull requests merged in 2023-01, with the labels that each got.

#2337 update(CI): upgrade toolchain in modern falco builder dockerfile
  docker/builder/modern-falco-builder.Dockerfile
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2336 chore(scripts/falco-driver-loader): improve curl resiliency
  scripts/falco-driver-loader
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2328 add deprecation warning for Mesos
  userspace/falco/app_actions/init_clients.cpp
  userspace/falco/app_cmdline_options.cpp
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/S, approved

#2331 new(falco): add --version-json to print version information in json format
  userspace/falco/app_actions/print_support.cpp
  userspace/falco/app_actions/print_version.cpp
  userspace/falco/app_cmdline_options.cpp
  userspace/falco/app_cmdline_options.h
  userspace/falco/application.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#2355 install ca-certificates in falco:no-driver image
  docker/no-driver/Dockerfile
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2365 fix(docker/falco): trust latest GPG key
  docker/falco/Dockerfile
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, area/ci

#2364 update(scripts): add option for regenerating signatures of all dev and release packages
  scripts/publish-deb
  scripts/publish-rpm
Labels: kind/feature, kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/L, area/ci

#2367 fix(scripts): fixed incorrect bash var expansion
  scripts/falco-driver-loader
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2363 new(userspace/falco): [EXPERIMENTAL] allow modern bpf probe to assign more than one CPU to a single ring buffer
  falco.yaml
  userspace/falco/app_actions/open_inspector.cpp
  userspace/falco/configuration.cpp
  userspace/falco/configuration.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2378 fix(userspace): use the right path for the `cpus_for_each_syscall_buffer` config
  userspace/falco/configuration.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2375 update(CI): mitigate frequent failure in CircleCI jobs
  docker/builder/modern-falco-builder.Dockerfile
Labels: kind/bug, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/build

#2381 build(cmake/modules): bump k8saudit to 0.5.0 and cloudtrail to 0.6.0
  cmake/modules/plugins.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#2382 docs(.github): rules are no longer in this repo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2383 build(cmake): upgrade falcoctl to v0.3.0-rc6
  cmake/modules/falcoctl.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#2392 update(cmake): bumped libs to 0.10.3
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS

#2391 fix(scripts): use falco-driver-loader only into install scripts
  scripts/debian/postinst.in
  scripts/rpm/postinstall.in
  scripts/systemd/falco-bpf.service
Labels: release-note, dco-signoff: yes, lgtm, size/S, approved, area/build
