Repository falcosecurity/falco, pull requests merged in 2023-08, with the labels that each got.

#2704 docs(README.md): minor improvements
  README.md
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2713 docs(brand): remove redundancy with the website
  brand/README.md
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#2726 update(userspace/engine): make rule_matching strategy stateless
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/falco/app/actions/init_falco_engine.cpp
  userspace/falco/app/actions/process_events.cpp
Labels: area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#2729 Relocate tools on Flatcar in BPF mode
  scripts/falco-driver-loader
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2728 Allow specifying explicit kernel release and version for `falco-driver-loader`
  scripts/falco-driver-loader
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved

#2677 feat(userspace): deprecate `-d` daemonize option
  userspace/falco/CMakeLists.txt
  userspace/falco/app/actions/actions.h
  userspace/falco/app/actions/daemonize.cpp
  userspace/falco/app/actions/init_outputs.cpp
  userspace/falco/app/actions/pidfile.cpp
  userspace/falco/app/app.cpp
  userspace/falco/app/options.cpp
  userspace/falco/app/options.h
  userspace/falco/falco.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#2742 cleanup: remove unused `--pidfile` option from systemd units
  scripts/systemd/falco-bpf.service
  scripts/systemd/falco-custom.service
  scripts/systemd/falco-kmod.service
  scripts/systemd/falco-modern-bpf.service
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2743 update(ci): minimize retention days for build-only CI artifacts
  .github/workflows/reusable_build_docker.yaml
  .github/workflows/reusable_build_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#2633 feat(userspace/outputs_http): Add option for mTLS
  falco.yaml
  userspace/falco/configuration.cpp
  userspace/falco/outputs_http.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#2744 cleanup: turn some warnings into errors
  userspace/falco/app/actions/process_events.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2410 #2393 Document why Falco is written in C++ rather than anything else
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#2746 chore: remove b64 from falco dependencies
  CMakeLists.txt
  userspace/falco/CMakeLists.txt
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#2747 update(cmake): support building libs and driver from forks
  cmake/modules/driver-repo/CMakeLists.txt
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs-repo/CMakeLists.txt
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#2748 fix(userspace/engine): support both old and new gcc + std::move
  userspace/engine/falco_engine.cpp
Labels: kind/bug, kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#2353 fix: falco-driver-loader source-only print env vars
  scripts/falco-driver-loader
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/L

#2751 fix: fix "ebpf_enabled" output stat
  userspace/falco/event_drops.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS
