Repository falcosecurity/falco, pull requests merged in 2024-07, with the labels that each got.

#3250 Added the OpenSSF Scorecard Badge
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3274 fix(ci): use vault.centos.org for centos:7 CI build.
  .github/workflows/reusable_build_packages.yaml
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, size/S, approved, area/ci

#3264 vote: add sgaist to OWNERS
  OWNERS
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS
