Repository falcosecurity/falco, pull requests merged in 2024-08, with the labels that each got.

#3272 fix(metrics/prometheus): adopt best prometheus practices for rules counters and sha256 file metrics
  userspace/falco/falco_metrics.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3292 chore(build): bump falcoctl to 0.9.0 for 0.38.2
  cmake/modules/falcoctl.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3291 Add Tulip Retail to adopters list
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3294 update(build): libs 0.17.3
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3293 new(docs): add changelog for 0.38.2
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3300 update(docs): update changelog for 0.38.2 (master branch)
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3305 feat(cmake): add conditional builds for falcoctl and rules paths
  cmake/modules/falcoctl.cmake
  cmake/modules/rules.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build, kind/release
