Repository falcosecurity/falco, pull requests merged in 2024-06, with the labels that each got.

#3233 chore(ci): enable dummy tests on the testing framework.
  .github/workflows/reusable_test_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/tests, area/ci

#3236 Revert #3135 "fix(engine): apply output substitutions for all sources"
  userspace/engine/rule_loader_compiler.cpp
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#3238 cleanup(falco): clarify that --print variants only affect syscalls
  userspace/falco/app/options.cpp
Labels: kind/documentation, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3239 update(engine): allow using -p to pass a format to plugin events
  userspace/engine/rule_loader_compiler.cpp
  userspace/falco/app/options.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3228 new(metrics): enable plugins metrics
  falco.yaml
  userspace/falco/configuration.cpp
  userspace/falco/falco_metrics.cpp
  userspace/falco/stats_writer.cpp
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/M, approved

#3262 update(docs): update CHANGELOG for 0.38.1
  CHANGELOG.md
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#3260 If rule compilation fails, return immediately
  userspace/engine/falco_engine.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS
