Repository falcosecurity/falco, pull requests merged in 2024-12, with the labels that each got.

#3216 add attestation for falco
  .github/workflows/release.yaml
  .github/workflows/reusable_build_docker.yaml
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, size/M, approved, area/build, kind/release

#3427 docs(falco.yaml): correct `buffered_outputs` description
  falco.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3436 chore(ci): enable jemalloc in musl build.
  .github/workflows/reusable_build_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci
