Repository falcosecurity/falco, pull requests merged in 2024-02, with the labels that each got.

#3053 fix(build): install libstdc++ in the Wolfi image
  docker/no-driver/Dockerfile.distroless
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3056 new(build): prune deb-dev and rpm-dev directories
  scripts/publish-deb
  scripts/publish-rpm
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/ci

#3060 fix(userspace/engine): always consider all rules (even the ones below min_prio) in m_rule_stats_manager
  userspace/engine/falco_engine.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#3064 fix(c++): add missing overrides
  userspace/falco/grpc_request_context.h
  userspace/falco/outputs_file.h
  userspace/falco/outputs_grpc.h
  userspace/falco/outputs_program.h
  userspace/falco/outputs_stdout.h
  userspace/falco/outputs_syslog.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved

#3062 fix(ci): update sync in deb and rpm scripts with acl
  scripts/publish-deb
  scripts/publish-rpm
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3065 refactor(userspace/engine): reduce allocations during rules loading
  userspace/engine/filter_macro_resolver.cpp
  userspace/engine/filter_macro_resolver.h
  userspace/engine/rule_loader_compiler.cpp
  userspace/engine/rule_loader_compiler.h
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3076 update(cmake): bumped falcoctl to v0.7.2.
  cmake/modules/falcoctl.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#3069 fix(c++): add missing explicit to single argument constructors
  unit_tests/engine/test_add_source.cpp
  unit_tests/engine/test_alt_rule_loader.cpp
  userspace/engine/evttype_index_ruleset.h
  userspace/engine/falco_common.h
  userspace/engine/falco_engine.h
  userspace/engine/filter_details_resolver.h
  userspace/engine/rule_loader.h
  userspace/falco/app/actions/process_events.cpp
  userspace/falco/app/restart_handler.h
  userspace/falco/falco_semaphore.h
  userspace/falco/grpc_context.h
  userspace/falco/grpc_request_context.cpp
  userspace/falco/versions_info.h
  userspace/falco/yaml_helper.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/tests

#3075 Added http headers option for driver download in docker images
  docker/driver-loader-legacy/docker-entrypoint.sh
  docker/driver-loader/docker-entrypoint.sh
  docker/falco/docker-entrypoint.sh
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/proposals

#3072 cleanup: minor adjustments to readme, add new testing section
  README.md
Labels: kind/documentation, release-note, dco-signoff: yes, lgtm, size/M, approved

#3080 sync(docs): cherrypick CHANGELOG entry for 0.37.1
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/S, approved, kind/release

#3088 cleanup(docker)!: remove unused builder dockerfile
  docker/builder/README.md
  docker/builder/modern-falco-builder.Dockerfile
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/M, approved, area/build

#3089 fix: Some compiler warnings
  cmake/modules/CompilerFlags.cmake
  unit_tests/engine/test_alt_rule_loader.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#3090 cleanup: falco_engine deps and include paths
  CMakeLists.txt
  userspace/engine/CMakeLists.txt
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3083 Improve const correctness
  unit_tests/test_falco_engine.h
  userspace/engine/evttype_index_ruleset.cpp
  userspace/engine/falco_common.cpp
  userspace/engine/falco_common.h
  userspace/engine/falco_engine.cpp
  userspace/engine/falco_engine.h
  userspace/engine/filter_ruleset.cpp
  userspace/engine/filter_ruleset.h
  userspace/engine/formats.cpp
  userspace/engine/formats.h
  userspace/engine/rule_loader.cpp
  userspace/engine/rule_loader_collector.cpp
  userspace/engine/rule_loader_compiler.cpp
  userspace/engine/rule_loader_reader.cpp
  userspace/falco/app/actions/actions.h
  userspace/falco/app/actions/configure_syscall_buffer_num.cpp
  userspace/falco/app/actions/helpers.h
  userspace/falco/app/actions/list_plugins.cpp
  userspace/falco/app/actions/load_config.cpp
  userspace/falco/app/actions/load_rules_files.cpp
  userspace/falco/app/actions/pidfile.cpp
  userspace/falco/app/actions/print_ignored_events.cpp
  userspace/falco/app/actions/print_kernel_version.cpp
  userspace/falco/app/actions/print_page_size.cpp
  userspace/falco/app/actions/print_plugin_info.cpp
  userspace/falco/app/actions/print_support.cpp
  userspace/falco/app/actions/print_syscall_events.cpp
  userspace/falco/app/actions/process_events.cpp
  userspace/falco/app/actions/validate_rules_files.cpp
  userspace/falco/app/app.cpp
  userspace/falco/configuration.cpp
  userspace/falco/event_drops.cpp
  userspace/falco/event_drops.h
  userspace/falco/falco_outputs.cpp
  userspace/falco/falco_outputs.h
  userspace/falco/logger.cpp
  userspace/falco/logger.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3093 cleanup(ci): make use of falcosecurity/testing provided composite action
  .github/workflows/reusable_test_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#3100 refactor: test AtomicSignalHandler.handle_once_wait_consistency
  unit_tests/engine/test_add_source.cpp
  unit_tests/engine/test_alt_rule_loader.cpp
  unit_tests/engine/test_plugin_requirements.cpp
  unit_tests/engine/test_rulesets.cpp
  unit_tests/falco/test_atomic_signal_handler.cpp
  userspace/engine/evttype_index_ruleset.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L, area/tests

#3099 cleanup: falco_engine test fixture
  unit_tests/CMakeLists.txt
  unit_tests/test_falco_engine.cpp
  unit_tests/test_falco_engine.h
Labels: kind/cleanup, size/XL, dco-signoff: yes, lgtm, release-note-none, approved, area/build, area/tests

#3105 fix(cmake): properly let falcoctl cmake module create `/usr/share/falco/plugins/` folder.
  cmake/modules/falcoctl.cmake
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3110 fix(ci): test-dev-packages-arm64 needs build-dev-packages-arm64.
  .github/workflows/ci.yml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3114 chore(ci): bumped codeql actions.
  .github/workflows/codeql.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3118 fix(ci): enforce bundled deps OFF in build-dev CI
  .github/workflows/reusable_build_dev.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3124 docs(README.md): Falco Graduates within the CNCF
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS
