Repository falcosecurity/falco, pull requests merged in 2024-09, with the labels that each got.

#3311 cleanup(userspace/falco)!: drop deprecated -t,-T,-D options.
  userspace/falco/app/actions/load_rules_files.cpp
  userspace/falco/app/options.cpp
  userspace/falco/app/options.h
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3312 new(userspace/falco): added `--config-schema` action to print config schema
  userspace/falco/CMakeLists.txt
  userspace/falco/app/actions/actions.h
  userspace/falco/app/actions/print_config_schema.cpp
  userspace/falco/app/app.cpp
  userspace/falco/app/options.cpp
  userspace/falco/app/options.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3315 ci(insecure-api): update semgrep docker image
  .github/workflows/insecure-api.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3316 update(cmake): bump falcoctl to v0.10.0-rc1
  cmake/modules/falcoctl.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3317 fix(ci): restore master and release CI workflow permissions.
  .github/workflows/master.yaml
  .github/workflows/release.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3314 new(falco): add json_include_message_property to have a message field without date and priority
  falco.yaml
  userspace/engine/formats.cpp
  userspace/engine/formats.h
  userspace/falco/app/actions/init_outputs.cpp
  userspace/falco/configuration.cpp
  userspace/falco/configuration.h
  userspace/falco/falco_outputs.cpp
  userspace/falco/falco_outputs.h
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/L

#3321 chore: scaffolding for enabling code formatting
  .clang-format
  .clang-format-ignore
  .cmake-format
  .cmake-format.json
  .git-blame-ignore-revs
  .github/workflows/format.yaml
  .pre-commit-config.yaml
  Contributing.md
  Makefile
  tools/local_hooks/dco-pre-commit-msg.sh
Labels: kind/feature, kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XXL, area/build, area/ci

#3324 update(falco_metrics): change prometheus rules metric naming
  falco.yaml
  userspace/falco/falco_metrics.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#3325 cleanup(falco): use header file for json schema
  userspace/engine/falco_engine.cpp
  userspace/engine/rule_json_schema.h
  userspace/falco/config_json_schema.h
  userspace/falco/configuration.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XXL

#3327 update(cmake): bump libs and driver to 0.18.0-rc2.
  cmake/modules/driver.cmake
  cmake/modules/falcoctl.cmake
  cmake/modules/falcosecurity-libs.cmake
  cmake/modules/rules.cmake
Labels: release-note, dco-signoff: yes, lgtm, size/S, approved, area/build, kind/release

#3329 chore(userspace/falco): deprecate `cri` related CLI options.
  userspace/falco/app/options.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#3330 update(cmake): bump libs to 0.18.0 and driver to 7.3.0+driver.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#3332 update(systemd): add falco.service alias to all systemd units
  scripts/systemd/falco-bpf.service
  scripts/systemd/falco-custom.service
  scripts/systemd/falco-modern-bpf.service
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3334 fix(userspace/falco): properly account for plugin with CAP_PARSING when computing interesting sc set
  userspace/falco/app/actions/configure_interesting_sets.cpp
  userspace/falco/app/actions/init_inspectors.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3343 chore(build): update libs to 0.18.1
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3344 feat(stats): add host_netinfo networking information stats family
  userspace/falco/stats_writer.cpp
Labels: kind/feature, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3347 sync: 0.39.x
  userspace/falco/stats_writer.cpp
Labels: dco-signoff: yes, lgtm, release-note-none, size/M, approved, kind/release

#3349 chore(build): update libs to 0.18.1 (master branch)
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3351 chore: ignore_some_files for clang format
  .clang-format-ignore
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3354 cleanup(falco): ignore lint commit
  .git-blame-ignore-revs
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3356 cleanup(falco): reformat options::define
  userspace/falco/app/options.cpp
Labels: kind/cleanup, area/engine, size/XL, dco-signoff: yes, lgtm, release-note-none, approved
