Repository falcosecurity/falco, pull requests merged in 2024-05, with the labels that each got.

#3184 refactor: smart pointer usage
  unit_tests/engine/test_alt_rule_loader.cpp
  userspace/engine/evttype_index_ruleset.cpp
  userspace/engine/falco_engine.cpp
  userspace/engine/rule_loader.h
  userspace/engine/stats_manager.cpp
  userspace/falco/app/actions/init_inspectors.cpp
  userspace/falco/app/actions/init_outputs.cpp
  userspace/falco/app/actions/load_plugins.cpp
  userspace/falco/app/actions/process_events.cpp
  userspace/falco/app/state.h
  userspace/falco/falco_outputs.cpp
  userspace/falco/falco_outputs.h
  userspace/falco/grpc_request_context.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3190 fix(userspace/falco): fix state inizialization.
  userspace/falco/app/state.h
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3191 update(cmake): bump falcoctl to v0.8.0-rc4
  cmake/modules/falcoctl.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release

#3193 update(falco): add deprecation notice for -T, -t and -D
  userspace/falco/app/options.cpp
Labels: kind/documentation, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#3199 update(cmake): bumped falcoctl to v0.8.0-rc5.
  cmake/modules/falcoctl.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release

#3201 new(ci): sign .tar.gz packages
  scripts/publish-bin
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/ci

#3203 fix(docker): added `zstd` dep to driver loader images
  docker/driver-loader-legacy/Dockerfile
  docker/falco/Dockerfile
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3204 update(cmake): bumped libs to 0.17.0-rc1 and falcoctl to v0.8.0-rc6.
  cmake/modules/driver.cmake
  cmake/modules/falcoctl.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build, kind/release

#3205 cleanup(metrics): add original rule name as label
  userspace/falco/falco_metrics.cpp
  userspace/falco/stats_writer.cpp
Labels: kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3211 update(cmake): bump libs to 0.17.0-rc2
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release

#3208 refactor(userspace): move falco logger under falco engine
  unit_tests/falco/test_atomic_signal_handler.cpp
  userspace/engine/CMakeLists.txt
  userspace/engine/evttype_index_ruleset.cpp
  userspace/engine/logger.cpp
  userspace/engine/logger.h
  userspace/falco/CMakeLists.txt
  userspace/falco/app/restart_handler.cpp
Labels: kind/bug, kind/cleanup, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3214 update(cmake): bump libs and driver to latest release
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build, kind/release

#3217 chore(build): bump rules to 3.1.0
  cmake/modules/rules.cmake
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3218 update(docs): update CHANGELOG for 0.38.0
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3224 update(docs): update CHANGELOG for 0.38.0 (master branch)
  CHANGELOG.md
Labels: kind/documentation, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3225 update(cmake): bump libs and driver to master.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release
