Repository falcosecurity/falco, pull requests merged in 2024-10, with the labels that each got.

#3357 update(changelog): add changelog for falco 0.39.0
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3359 update(changelog): add changelog for falco 0.39.0
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/L

#3368 fix(userspace/falco): fix event set selection for plugin with parsing capability
  userspace/falco/app/actions/configure_interesting_sets.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved

#3360 new(ci): add a workflow to automatically bump libs on each monday.
  .github/workflows/bump-libs.yaml
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, size/M, approved, area/ci

#3363 fix(engine): disable comma separated vectors in cxxopts
  userspace/falco/app/options.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3369 fix(ci): fixed bump-libs workflow syntax.
  .github/workflows/bump-libs.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#3373 update(changelog): updated changelog for 0.39.1.
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/S, approved, kind/release

#3376 chore(ci): use redhat advised method to check rpmsign success.
  .github/workflows/reusable_publish_packages.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3379 fix(ci): fixed shasum computation for bump-libs CI.
  .github/workflows/bump-libs.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci

#3375 Make enable()/disable() virtual so they can be overridden
  userspace/engine/indexable_ruleset.h
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3389 update(cmake): bump libs to latest master.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release
