Repository falcosecurity/falco, pull requests merged in 2025-02, with the labels that each got.

#3478 fix(userspace/falco): fix jemalloc enabled in minimal build.
  userspace/falco/stats_writer.cpp
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, approved, size/XS

#3487 Add NETWAYS Web Services to ADOPTERS.md
  ADOPTERS.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3483 feat(falco/app): move actions not using config before `load_config`
  userspace/falco/app/app.cpp
Labels: kind/feature, area/engine, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3484 refactor(falco/app): apply early return pattern in actions code
  userspace/falco/app/actions/init_falco_engine.cpp
  userspace/falco/app/actions/init_inspectors.cpp
  userspace/falco/app/actions/list_fields.cpp
  userspace/falco/app/actions/list_plugins.cpp
  userspace/falco/app/actions/load_plugins.cpp
  userspace/falco/app/actions/pidfile.cpp
  userspace/falco/app/actions/print_config_schema.cpp
  userspace/falco/app/actions/print_generated_gvisor_config.cpp
  userspace/falco/app/actions/print_help.cpp
  userspace/falco/app/actions/print_kernel_version.cpp
  userspace/falco/app/actions/print_page_size.cpp
  userspace/falco/app/actions/print_plugin_info.cpp
  userspace/falco/app/actions/print_rule_schema.cpp
  userspace/falco/app/actions/print_support.cpp
  userspace/falco/app/actions/print_syscall_events.cpp
  userspace/falco/app/actions/print_version.cpp
  userspace/falco/app/actions/start_grpc_server.cpp
  userspace/falco/app/actions/start_webserver.cpp
  userspace/falco/app/actions/validate_rules_files.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XXL

#3490 fix(cmake): add support for 16K kernel page to jemalloc
  cmake/modules/jemalloc.cmake
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#3492 fix(docker): fixed entrypoints paths with new docker context.
  docker/driver-loader-buster/Dockerfile
  docker/driver-loader/Dockerfile
  docker/falco-debian/Dockerfile
  docker/falco/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#3505 fix(userspace/falco): when counting `-M` timeout, do not account for async events
  userspace/falco/app/actions/process_events.cpp
Labels: kind/bug, area/engine, dco-signoff: yes, lgtm, release-note-none, size/S, approved
