Repository falcosecurity/falco, pull requests merged in 2025-06, with the labels that each got.

#3585 fix(userspace/falco): when collecting metrics for stats_writer, create a `libs_metrics_collector` for each source
  userspace/falco/app/actions/process_events.cpp
  userspace/falco/stats_writer.cpp
  userspace/falco/stats_writer.h
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/M, approved

#3600 update(docs): cherry pick CHANGELOG.
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3598 fix(cmake): fix abseil-cpp under alpine build
  cmake/modules/grpc.cmake
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3611 update(build): update container plugin to 0.2.6
  CMakeLists.txt
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3596 chore(falco.yaml): clean up plugins config leftover
  falco.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3622 update(CHANGELOG.md): release 0.41.2
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3621 docs(RELEASE.md): fix and reword some parts
  RELEASE.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3629 sync(0.41.0): bump container plugin to 0.3.1.
  CMakeLists.txt
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build
