Repository falcosecurity/falco, pull requests merged in 2025-07, with the labels that each got.

#3633 update(CHANGELOG.md): release 0.41.3
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3634 update(CHANGELOG.md): release 0.41.3 (cherry-pick)
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/S, approved

#3644 build: fix `debian:buster` apt debian repo URL in driver-loader-buster
  docker/driver-loader-buster/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3640 fix(restart_handler): disable if there is no work
  userspace/falco/app/restart_handler.cpp
  userspace/falco/app/restart_handler.h
Labels: kind/bug, area/engine, release-note, dco-signoff: yes, lgtm, size/S, approved
