Repository falcosecurity/falco, pull requests merged in 2025-01, with the labels that each got.

#3442 chore: avoid deprecated funcs to calculate sha256
  userspace/engine/falco_utils.cpp
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/build

#3447 update(ci): use 4cpu-16gb arm runners
  .github/workflows/reusable_build_dev.yaml
  .github/workflows/reusable_build_docker.yaml
  .github/workflows/reusable_build_packages.yaml
  .github/workflows/reusable_test_packages.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#3450 update(build): relax dkms dependencies to suggestions in DEB and RPM packages
  cmake/modules/CPackConfig.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3449 chore(docs): update `plugins_hostinfo` config file comment.
  falco.yaml
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3451 chore(docker): drop unused libelf dep from container images
  docker/driver-loader-buster/Dockerfile
  docker/driver-loader/Dockerfile
  docker/falco-debian/Dockerfile
  docker/falco/Dockerfile
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3453 fix(userspace/falco): use container_engines.cri.sockets in load_yaml
  userspace/falco/configuration.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3457 update(cmake): bump libs to 0.20.0 and driver to 8.0.0+driver.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/build

#3459 fix(ci): fixed reusable_build/publish_docker workflows.
  .github/workflows/reusable_build_docker.yaml
  .github/workflows/reusable_publish_docker.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, size/S, approved, area/ci

#3458 chore(falco.yaml): remove comments about cri cli arguments
  falco.yaml
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3467 update(cmake): bump falcoctl to v0.11.0
  cmake/modules/falcoctl.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3469 update(docs): update changelog
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/M, approved, kind/release

#3470 chore(docs): updated changelog for 0.40.0
  CHANGELOG.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/M, approved, kind/release

#3472 chore: add back Falco static package to the release template.
  .github/release_template.md
Labels: kind/cleanup, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/ci
