Repository falcosecurity/falco, pull requests merged in 2025-05, with the labels that each got.

#3559 fix(cmake): fix bundled c-ares cmake issue with e.g. SLES
  cmake/modules/cares.cmake
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3556 fix(build): fixed container custom_target `sed` command.
  CMakeLists.txt
Labels: kind/bug, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3565 update(cmake): bump libs and driver to latest tagged releases.
  cmake/modules/driver.cmake
  cmake/modules/falcosecurity-libs.cmake
Labels: dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build, kind/release

#3566 cleanup(userspace/falco): drop unused `libs_metrics_collector` variable.
  userspace/falco/falco_metrics.cpp
Labels: kind/cleanup, area/engine, dco-signoff: yes, lgtm, release-note-none, approved, size/XS

#3567 update(cmake/rules): bump to falco-rules-4.0.0-rc1
  cmake/modules/rules.cmake
Labels: kind/feature, dco-signoff: yes, lgtm, release-note-none, approved, size/XS, area/build

#3577 update(cmake): bumped falcoctl to 0.11.1 and rules to 4.0.0.
  cmake/modules/falcoctl.cmake
  cmake/modules/rules.cmake
Labels: kind/cleanup, release-note, dco-signoff: yes, lgtm, size/S, approved, area/build

#3586 update(docs): bumped changelog for release 0.41.0, master sync
  CHANGELOG.md
Labels: kind/documentation, dco-signoff: yes, lgtm, release-note-none, size/M, approved
